import { NextResponse } from "next/server";

export async function GET() {
  const portfolios = {
    personal: [
      {
        id: "1",
        name: "Alex portfolio #1",
        description: "COVID-19. Battle-tested stocks.",
        value: 26950.0,
        change: 2450.0,
        changePercent: 10.01,
        stocks: 12,
        modified: "Aug 8",
        assets: [
          {
            id: "1",
            symbol: "AAPL",
            name: "Apple Inc.",
            type: "stocks",
            quantity: 50,
            avgBuyPrice: 150.25,
            currentPrice: 175.3,
            value: 8765.0,
          },
          {
            id: "2",
            symbol: "MSFT",
            name: "Microsoft Corporation",
            type: "stocks",
            quantity: 30,
            avgBuyPrice: 280.5,
            currentPrice: 310.75,
            value: 9322.5,
          },
          {
            id: "3",
            symbol: "GOOGL",
            name: "Alphabet Inc.",
            type: "stocks",
            quantity: 15,
            avgBuyPrice: 2450.0,
            currentPrice: 2580.25,
            value: 38703.75,
          },
          {
            id: "4",
            symbol: "TSLA",
            name: "Tesla Inc.",
            type: "stocks",
            quantity: 25,
            avgBuyPrice: 220.8,
            currentPrice: 195.45,
            value: 4886.25,
          },
          {
            id: "5",
            symbol: "GLD",
            name: "SPDR Gold Trust",
            type: "commodities",
            quantity: 100,
            avgBuyPrice: 180.25,
            currentPrice: 185.9,
            value: 18590.0,
          },
          {
            id: "6",
            symbol: "VTI",
            name: "Vanguard Total Stock Market ETF",
            type: "bonds",
            quantity: 75,
            avgBuyPrice: 210.5,
            currentPrice: 225.8,
            value: 16935.0,
          },
          {
            id: "7",
            symbol: "REIT-1",
            name: "Downtown Office Complex",
            type: "real estate",
            quantity: 1,
            avgBuyPrice: 125000.0,
            currentPrice: 135000.0,
            value: 135000.0,
          },
        ],
      },
      {
        id: "2",
        name: "Growth Portfolio",
        description: "High-growth technology and innovation stocks.",
        value: 45200.0,
        change: 3200.0,
        changePercent: 7.62,
        stocks: 8,
        modified: "Aug 7",
        assets: [
          {
            id: "8",
            symbol: "NVDA",
            name: "NVIDIA Corporation",
            type: "stocks",
            quantity: 20,
            avgBuyPrice: 420.5,
            currentPrice: 485.75,
            value: 9715.0,
          },
          {
            id: "9",
            symbol: "AMD",
            name: "Advanced Micro Devices",
            type: "stocks",
            quantity: 40,
            avgBuyPrice: 95.25,
            currentPrice: 110.8,
            value: 4432.0,
          },
          {
            id: "10",
            symbol: "AMZN",
            name: "Amazon.com Inc.",
            type: "stocks",
            quantity: 12,
            avgBuyPrice: 3200.0,
            currentPrice: 3450.25,
            value: 41403.0,
          },
        ],
      },
      {
        id: "3",
        name: "Dividend Income",
        description: "Stable dividend-paying stocks for income generation.",
        value: 32800.0,
        change: -850.0,
        changePercent: -2.53,
        stocks: 15,
        modified: "Aug 6",
        assets: [
          {
            id: "11",
            symbol: "JNJ",
            name: "Johnson & Johnson",
            type: "stocks",
            quantity: 60,
            avgBuyPrice: 165.5,
            currentPrice: 158.25,
            value: 9495.0,
          },
          {
            id: "12",
            symbol: "KO",
            name: "The Coca-Cola Company",
            type: "stocks",
            quantity: 80,
            avgBuyPrice: 58.75,
            currentPrice: 61.2,
            value: 4896.0,
          },
          {
            id: "13",
            symbol: "PG",
            name: "Procter & Gamble Co.",
            type: "stocks",
            quantity: 45,
            avgBuyPrice: 145.8,
            currentPrice: 142.5,
            value: 6412.5,
          },
        ],
      },
    ],
  };

  return NextResponse.json(portfolios);
}
